// Code generated by MockGen. DO NOT EDIT.
// Source: internal/url/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/url/interface.go -destination=internal/mocks/shortener.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/wickedv43/go-shortener/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockShortener is a mock of Shortener interface.
type MockShortener struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerMockRecorder
	isgomock struct{}
}

// MockShortenerMockRecorder is the mock recorder for MockShortener.
type MockShortenerMockRecorder struct {
	mock *MockShortener
}

// NewMockShortener creates a new mock instance.
func NewMockShortener(ctrl *gomock.Controller) *MockShortener {
	mock := &MockShortener{ctrl: ctrl}
	mock.recorder = &MockShortenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortener) EXPECT() *MockShortenerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockShortener) Delete(inCh chan string) chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", inCh)
	ret0, _ := ret[0].(chan string)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShortenerMockRecorder) Delete(inCh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShortener)(nil).Delete), inCh)
}

// DeleteBatch mocks base method.
func (m *MockShortener) DeleteBatch(shorts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", shorts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockShortenerMockRecorder) DeleteBatch(shorts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockShortener)(nil).DeleteBatch), shorts)
}

// DeleteUserURLS mocks base method.
func (m *MockShortener) DeleteUserURLS(ctx context.Context, userID int, shorts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserURLS", ctx, userID, shorts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserURLS indicates an expected call of DeleteUserURLS.
func (mr *MockShortenerMockRecorder) DeleteUserURLS(ctx, userID, shorts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserURLS", reflect.TypeOf((*MockShortener)(nil).DeleteUserURLS), ctx, userID, shorts)
}

// FanIn mocks base method.
func (m *MockShortener) FanIn(chs ...chan string) chan string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range chs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FanIn", varargs...)
	ret0, _ := ret[0].(chan string)
	return ret0
}

// FanIn indicates an expected call of FanIn.
func (mr *MockShortenerMockRecorder) FanIn(chs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FanIn", reflect.TypeOf((*MockShortener)(nil).FanIn), chs...)
}

// Gen mocks base method.
func (m *MockShortener) Gen(shorts ...string) chan string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range shorts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Gen", varargs...)
	ret0, _ := ret[0].(chan string)
	return ret0
}

// Gen indicates an expected call of Gen.
func (mr *MockShortenerMockRecorder) Gen(shorts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gen", reflect.TypeOf((*MockShortener)(nil).Gen), shorts...)
}

// Get mocks base method.
func (m *MockShortener) Get(ctx context.Context, shortID string) (storage.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortID)
	ret0, _ := ret[0].(storage.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShortenerMockRecorder) Get(ctx, shortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShortener)(nil).Get), ctx, shortID)
}

// GetAll mocks base method.
func (m *MockShortener) GetAll(ctx context.Context, userID int) ([]storage.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID)
	ret0, _ := ret[0].([]storage.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockShortenerMockRecorder) GetAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockShortener)(nil).GetAll), ctx, userID)
}

// HealthCheck mocks base method.
func (m *MockShortener) HealthCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockShortenerMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockShortener)(nil).HealthCheck))
}

// Save mocks base method.
func (m *MockShortener) Save(ctx context.Context, originalURL string, userID int) (storage.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, originalURL, userID)
	ret0, _ := ret[0].(storage.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockShortenerMockRecorder) Save(ctx, originalURL, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockShortener)(nil).Save), ctx, originalURL, userID)
}

// Stats mocks base method.
func (m *MockShortener) Stats() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Stats indicates an expected call of Stats.
func (mr *MockShortenerMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockShortener)(nil).Stats))
}
