  syntax = "proto3";

  package grpc;

  option go_package = "/internal/grpc";

  import "google/protobuf/empty.proto";

  message CreateRequest {
    string url = 1;
    int32 user_id = 2;
  }

  message CreateResponse {
    string short_url = 1;
  }

  message GetShortRequest {
    string short_url = 1;
  }

  message GetShortResponse {
    string original_url = 1;
  }

  message BatchRequest {
    message Item {
      string correlation_id = 1;
      string original_url = 2;
    }
    int32 user_id = 1;
    repeated Item urls = 2;
  }

  message BatchResponse {
    message Item {
      string correlation_id = 1;
      string short_url = 2;
    }
    repeated Item urls = 1;
  }

  message GetAllRequest {
    int32 user_id = 1;
  }

  message URLData {
    string short_url = 1;
    string original_url = 2;
  }

  message GetAllResponse {
    repeated URLData urls = 1;
  }

  message DeleteUserURLsRequest {
    int32 user_id = 1;
    repeated string short_urls = 2;
  }

  message DeleteUserURLsResponse {
    int32 deleted_count = 1;
  }

  message StatsResponse {
    int32 urls = 1;
    int32 users = 2;
  }

  service Shortener {
    rpc Create(CreateRequest) returns (CreateResponse);
    rpc GetShort(GetShortRequest) returns (GetShortResponse);
    rpc Batch(BatchRequest) returns (BatchResponse);
    rpc GetAll(GetAllRequest) returns (GetAllResponse);
    rpc DeleteUserURLs(DeleteUserURLsRequest) returns (DeleteUserURLsResponse);
    rpc Stats(google.protobuf.Empty) returns (StatsResponse);
    rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty); // можно добавить ping
  }
